### ISSUE TITLE
Reports problem

### ISSUE THREAD

**Issue by rhzeto** [Anof-cyber/APTRS#3]
New, clean installation -->  installation was successful with install.sh --> report for project "JUICE SHOP" (example):
http://localhost:8000/project/report/pdf/25/

get:
Server Error (500)

**Comment by Anof-cyber** [comment]
Make sure you have installed the pdf library `wkhtmltopdf` version 0.12.6.

If yes kindly confirm the same with below command in your cmd or terminal
`wkhtmltopdf --version`

**Comment by silent6trinity** [comment]
I've tried troubleshooting this as well, and it results in a slew of errors from wkhtmltopdf, and many of it is a result of `wkhtmltox depends on libjpeg-turbo8; however: Package libjpeg-turbo8 is not installed`

this may be because we're trying on Kali Linux as opposed to Ubuntu- but understand that many of your users will probably be trying to use this tool _from_ Kali Linux.

**Comment by Anof-cyber** [comment]
The same is already mentioned in the documentation as well. If you are getting errors with reporting you need to install the `wkhtmltopdf ` manually based on your system and os. 

If you are using kali you need to download the Debian file based on your Architecture from https://wkhtmltopdf.org/downloads.html

**Comment by shyam0904a** [comment]
> New, clean installation --> installation was successful with install.sh --> report for project "JUICE SHOP" (example): http://localhost:8000/project/report/pdf/25/
> 
> get: Server Error (500)

Make the sqlite DB file executable will do the job:)

**Comment by silent6trinity** [comment]
> The same is already mentioned in the documentation as well. If you are getting errors with reporting you need to install the `wkhtmltopdf ` manually based on your system and os.
> 
> If you are using kali you need to download the Debian file based on your Architecture from https://wkhtmltopdf.org/downloads.html

I've followed your documentation and have tried troubleshooting extensively. Regardless the version of wkhtmltopdf, I end up with this error (After enabling `DEBUG` in `settings.py`:

`wkhtmltopdf reported an error:
The switch --footer-font-name, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --toc-header-text, is not support using unpatched qt, and will be ignored.The switch --xsl-style-sheet, is not support using unpatched qt, and will be ignored.The switch --disable-dotted-lines, is not support using unpatched qt, and will be ignored.Error: This version of wkhtmltopdf is built against an unpatched version of QT, and does not support more than one input document.
Exit with code 1, due to unknown error.`

**Comment by Anof-cyber** [comment]
The issues were fixed in the latest version of wkhtmltopdf. Kindly check if you have downloaded the Linux version from this
https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6.1-2

**Comment by silent6trinity** [comment]
> AMD 64 - https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb

Wow, that one worked perfectly. I couldn't find one with the proper Qt patch, thank you
