### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by wormy638** [Anof-cyber/APTRS#5]
Linux Mint 21
Getting a "server 500" error when attempting to view the report from the example project or a created project using the PDF button. 
Did receive the following warning when installing:
"DEPRECATION: pdfkit is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559" 

Not sure where server logs are being stored, so I can't provide any other details.

**Comment by Anof-cyber** [comment]
The issue is with the PIP and pdfkit. Still, could you confirm the python and pip versions? Also, can you try installing the library manually with `pip3 install pdfkit`

Also, can you check if the `wkhtmltopdf` library is installed with the correct version and added to the system environment?
Use `wkhtmltopdf  --version` in your terminal to confirm.

**Comment by wormy638** [comment]
Installed pdfkit with pip3 with no issues. 
wkhtmltopdf was not installed on my system, installed and added to the environment.
python version: 3.10
pip version: 22.0.2 (3.10)
wkhtmltopdf version: 0.12.6

Still getting the 500 error

**Comment by Anof-cyber** [comment]
The error is probably from `wkhtmltopdf `. If you have installed it with `apt` remove it and install it manually with deb file.

**Comment by wormy638** [comment]
It sure was. Appreciate the help and looking forward to putting this to work!
